import mongoose from "mongoose";
import dotenv from "dotenv";
import MenuItem from "./models/MenuItem.js";

dotenv.config();

const MENU_DATA = [
  {
    "title": "Signature Espresso",
    "desc": "A bold, concentrated espresso with a rich crema.",
    "price": 150,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/espresso.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-01"
  },
  {
    "title": "Americano",
    "desc": "Smooth espresso balanced with hot water for a clean finish.",
    "price": 160,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/americano.webp",
    "featured": false,
    "available": true,
    "itemId": "coffee-02"
  },
  {
    "title": "Cappuccino",
    "desc": "Rich espresso topped with silky steamed milk and thick foam.",
    "price": 180,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/cappuccino.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-03"
  },
  {
    "title": "Classic Latte",
    "desc": "Smooth espresso blended with warm, creamy steamed milk.",
    "price": 190,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/latte.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-04"
  },
  {
    "title": "Vanilla Latte",
    "desc": "Silky espresso and steamed milk finished with vanilla.",
    "price": 220,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/vanilla-latte.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-05"
  },
  {
    "title": "Caramel Latte",
    "desc": "Creamy espresso latte with a delicate caramel sweetness.",
    "price": 230,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/caramel-latte.webp",
    "featured": false,
    "available": true,
    "itemId": "coffee-06"
  },
  {
    "title": "Mocha",
    "desc": "Espresso blended with rich chocolate and steamed milk.",
    "price": 240,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/mocha.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-07"
  },
  {
    "title": "Hazelnut Cappuccino",
    "desc": "Classic cappuccino with roasted hazelnut and creamy foam.",
    "price": 230,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/hazelnut-cappuccino.webp",
    "featured": false,
    "available": true,
    "itemId": "coffee-08"
  },
  {
    "title": "Flat White",
    "desc": "Velvety microfoam layered over a double espresso.",
    "price": 200,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/flat-white.webp",
    "featured": false,
    "available": true,
    "itemId": "coffee-09"
  },
  {
    "title": "Cold Brew",
    "desc": "Slow-steeped for 18 hours for a smooth, naturally sweet finish.",
    "price": 200,
    "type": "veg",
    "category": "Coffee",
    "section": "drinks",
    "image": "/menu/cold-brew.webp",
    "featured": true,
    "available": true,
    "itemId": "coffee-10"
  },
  {
    "title": "Masala Chai",
    "desc": "Black tea slowly brewed with warming Indian spices.",
    "price": 120,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/masala-chai.webp",
    "featured": true,
    "available": true,
    "itemId": "tea-01"
  },
  {
    "title": "Classic Black Tea",
    "desc": "A comforting cup of fragrant black tea.",
    "price": 110,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/black-tea.webp",
    "featured": false,
    "available": true,
    "itemId": "tea-02"
  },
  {
    "title": "Green Tea",
    "desc": "Light and refreshing green tea with a clean finish.",
    "price": 140,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/green-tea.webp",
    "featured": false,
    "available": true,
    "itemId": "tea-03"
  },
  {
    "title": "Lemon Ginger Tea",
    "desc": "Fresh lemon and ginger infused into fragrant black tea.",
    "price": 150,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/lemon-ginger-tea.webp",
    "featured": false,
    "available": true,
    "itemId": "tea-04"
  },
  {
    "title": "Peach Iced Tea",
    "desc": "Chilled tea with delicate peach and a refreshing finish.",
    "price": 170,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/peach-iced-tea.webp",
    "featured": false,
    "available": true,
    "itemId": "tea-05"
  },
  {
    "title": "Mint Green Tea",
    "desc": "Green tea brightened with fresh mint leaves.",
    "price": 150,
    "type": "veg",
    "category": "Tea",
    "section": "drinks",
    "image": "/menu/mint-green-tea.webp",
    "featured": false,
    "available": true,
    "itemId": "tea-06"
  },
  {
    "title": "Classic Cold Coffee",
    "desc": "Creamy chilled coffee blended until perfectly smooth.",
    "price": 190,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/cold-coffee.webp",
    "featured": true,
    "available": true,
    "itemId": "cold-01"
  },
  {
    "title": "Mocha Frappe",
    "desc": "Chilled mocha blended with ice and finished with soft cream.",
    "price": 220,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/mocha-frappe.webp",
    "featured": true,
    "available": true,
    "itemId": "cold-02"
  },
  {
    "title": "Caramel Frappe",
    "desc": "Cold blended coffee with caramel and a creamy finish.",
    "price": 230,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/caramel-frappe.webp",
    "featured": false,
    "available": true,
    "itemId": "cold-03"
  },
  {
    "title": "Vanilla Frappe",
    "desc": "Smooth vanilla coffee blended with ice and milk.",
    "price": 220,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/vanilla-frappe.webp",
    "featured": false,
    "available": true,
    "itemId": "cold-04"
  },
  {
    "title": "Fresh Lemon Cooler",
    "desc": "Bright lemon, chilled water and a refreshing citrus finish.",
    "price": 150,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/lemon-cooler.webp",
    "featured": false,
    "available": true,
    "itemId": "cold-05"
  },
  {
    "title": "Strawberry Milkshake",
    "desc": "Creamy strawberry shake made with real strawberries.",
    "price": 220,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/strawberry-shake.webp",
    "featured": true,
    "available": true,
    "itemId": "cold-06"
  },
  {
    "title": "Chocolate Milkshake",
    "desc": "Rich chocolate blended with chilled milk and ice cream.",
    "price": 230,
    "type": "veg",
    "category": "Cold Beverages",
    "section": "drinks",
    "image": "/menu/chocolate-shake.webp",
    "featured": false,
    "available": true,
    "itemId": "cold-07"
  },
  {
    "title": "Classic Breakfast Plate",
    "desc": "Toast, eggs, sautéed vegetables and fresh seasonal sides.",
    "price": 280,
    "type": "non-veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/breakfast-plate.webp",
    "featured": true,
    "available": true,
    "itemId": "breakfast-01"
  },
  {
    "title": "Avocado Toast",
    "desc": "Toasted sourdough topped with creamy avocado and herbs.",
    "price": 240,
    "type": "veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/avocado-toast.webp",
    "featured": true,
    "available": true,
    "itemId": "breakfast-02"
  },
  {
    "title": "Pancake Stack",
    "desc": "Fluffy pancakes with maple syrup, butter and fresh berries.",
    "price": 260,
    "type": "veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/pancakes.webp",
    "featured": true,
    "available": true,
    "itemId": "breakfast-03"
  },
  {
    "title": "French Toast",
    "desc": "Golden brioche toast with cinnamon, berries and maple syrup.",
    "price": 250,
    "type": "veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/french-toast.webp",
    "featured": false,
    "available": true,
    "itemId": "breakfast-04"
  },
  {
    "title": "Granola Bowl",
    "desc": "Crunchy granola with yogurt, honey and seasonal fruits.",
    "price": 220,
    "type": "veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/granola-bowl.webp",
    "featured": false,
    "available": true,
    "itemId": "breakfast-05"
  },
  {
    "title": "Veg Omelette",
    "desc": "Fluffy omelette with peppers, onions, herbs and cheese.",
    "price": 200,
    "type": "non-veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/veg-omelette.webp",
    "featured": false,
    "available": true,
    "itemId": "breakfast-06"
  },
  {
    "title": "Breakfast Croissant",
    "desc": "Buttery croissant filled with egg, cheese and fresh greens.",
    "price": 230,
    "type": "non-veg",
    "category": "Breakfast",
    "section": "food",
    "image": "/menu/breakfast-croissant.webp",
    "featured": false,
    "available": true,
    "itemId": "breakfast-07"
  },
  {
    "title": "Grilled Sandwich",
    "desc": "Golden toasted bread layered with vegetables and cheese.",
    "price": 220,
    "type": "veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/grilled-sandwich.webp",
    "featured": true,
    "available": true,
    "itemId": "sandwich-01"
  },
  {
    "title": "Pesto Chicken Melt",
    "desc": "Grilled chicken, basil pesto and melted cheese in sourdough.",
    "price": 280,
    "type": "non-veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/pesto-chicken-melt.webp",
    "featured": true,
    "available": true,
    "itemId": "sandwich-02"
  },
  {
    "title": "Caprese Toastie",
    "desc": "Mozzarella, tomato, basil and pesto on toasted sourdough.",
    "price": 240,
    "type": "veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/caprese-toastie.webp",
    "featured": false,
    "available": true,
    "itemId": "sandwich-03"
  },
  {
    "title": "Cheese Corn Sandwich",
    "desc": "Creamy corn and melted cheese grilled until golden.",
    "price": 210,
    "type": "veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/cheese-corn-sandwich.webp",
    "featured": false,
    "available": true,
    "itemId": "sandwich-04"
  },
  {
    "title": "Chicken Club Sandwich",
    "desc": "Grilled chicken, lettuce, tomato, cheese and house mayo.",
    "price": 320,
    "type": "non-veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/chicken-club.webp",
    "featured": true,
    "available": true,
    "itemId": "sandwich-05"
  },
  {
    "title": "Mushroom Melt",
    "desc": "Sautéed mushrooms, caramelized onions and melted cheese.",
    "price": 250,
    "type": "veg",
    "category": "Sandwiches",
    "section": "food",
    "image": "/menu/mushroom-melt.webp",
    "featured": false,
    "available": true,
    "itemId": "sandwich-06"
  },
  {
    "title": "Classic Veg Burger",
    "desc": "Crispy vegetable patty with lettuce, tomato and house sauce.",
    "price": 240,
    "type": "veg",
    "category": "Burgers",
    "section": "food",
    "image": "/menu/veg-burger.webp",
    "featured": false,
    "available": true,
    "itemId": "burger-01"
  },
  {
    "title": "Chicken Burger",
    "desc": "Juicy grilled chicken patty with lettuce, cheese and spicy mayo.",
    "price": 320,
    "type": "non-veg",
    "category": "Burgers",
    "section": "food",
    "image": "/menu/chicken-burger.webp",
    "featured": true,
    "available": true,
    "itemId": "burger-02"
  },
  {
    "title": "Crispy Chicken Burger",
    "desc": "Crunchy chicken fillet with lettuce and creamy house sauce.",
    "price": 340,
    "type": "non-veg",
    "category": "Burgers",
    "section": "food",
    "image": "/menu/crispy-chicken-burger.webp",
    "featured": true,
    "available": true,
    "itemId": "burger-03"
  },
  {
    "title": "Mushroom Swiss Burger",
    "desc": "Grilled mushroom patty with Swiss cheese and caramelized onions.",
    "price": 290,
    "type": "veg",
    "category": "Burgers",
    "section": "food",
    "image": "/menu/mushroom-burger.webp",
    "featured": false,
    "available": true,
    "itemId": "burger-04"
  },
  {
    "title": "Creamy Alfredo Pasta",
    "desc": "Creamy parmesan sauce with tender chicken and herbs.",
    "price": 320,
    "type": "non-veg",
    "category": "Pasta",
    "section": "food",
    "image": "/menu/alfredo-pasta.webp",
    "featured": true,
    "available": true,
    "itemId": "pasta-01"
  },
  {
    "title": "Arrabbiata Pasta",
    "desc": "Penne tossed in a rich tomato sauce with garlic and herbs.",
    "price": 260,
    "type": "veg",
    "category": "Pasta",
    "section": "food",
    "image": "/menu/arrabbiata-pasta.webp",
    "featured": true,
    "available": true,
    "itemId": "pasta-02"
  },
  {
    "title": "Pesto Pasta",
    "desc": "Pasta tossed with fresh basil pesto, parmesan and cherry tomatoes.",
    "price": 280,
    "type": "veg",
    "category": "Pasta",
    "section": "food",
    "image": "/menu/pesto-pasta.webp",
    "featured": false,
    "available": true,
    "itemId": "pasta-03"
  },
  {
    "title": "Creamy Mushroom Pasta",
    "desc": "Silky cream sauce with sautéed mushrooms and herbs.",
    "price": 290,
    "type": "veg",
    "category": "Pasta",
    "section": "food",
    "image": "/menu/mushroom-pasta.webp",
    "featured": false,
    "available": true,
    "itemId": "pasta-04"
  },
  {
    "title": "Spicy Chicken Penne",
    "desc": "Penne with grilled chicken, peppers and a spicy tomato sauce.",
    "price": 320,
    "type": "non-veg",
    "category": "Pasta",
    "section": "food",
    "image": "/menu/spicy-chicken-pasta.webp",
    "featured": true,
    "available": true,
    "itemId": "pasta-05"
  },
  {
    "title": "Classic French Fries",
    "desc": "Crispy golden fries seasoned with sea salt.",
    "price": 150,
    "type": "veg",
    "category": "Sides",
    "section": "food",
    "image": "/menu/fries.webp",
    "featured": false,
    "available": true,
    "itemId": "side-01"
  },
  {
    "title": "Peri Peri Fries",
    "desc": "Crispy fries tossed in our signature peri peri seasoning.",
    "price": 170,
    "type": "veg",
    "category": "Sides",
    "section": "food",
    "image": "/menu/peri-peri-fries.webp",
    "featured": true,
    "available": true,
    "itemId": "side-02"
  },
  {
    "title": "Cheese Fries",
    "desc": "Golden fries topped with warm creamy cheese sauce.",
    "price": 200,
    "type": "veg",
    "category": "Sides",
    "section": "food",
    "image": "/menu/cheese-fries.webp",
    "featured": false,
    "available": true,
    "itemId": "side-03"
  },
  {
    "title": "Garlic Bread",
    "desc": "Toasted bread brushed with garlic butter and herbs.",
    "price": 160,
    "type": "veg",
    "category": "Sides",
    "section": "food",
    "image": "/menu/garlic-bread.webp",
    "featured": false,
    "available": true,
    "itemId": "side-04"
  },
  {
    "title": "Cheesy Garlic Bread",
    "desc": "Golden garlic bread finished with melted mozzarella.",
    "price": 200,
    "type": "veg",
    "category": "Sides",
    "section": "food",
    "image": "/menu/cheesy-garlic-bread.webp",
    "featured": true,
    "available": true,
    "itemId": "side-05"
  },
  {
    "title": "Chocolate Fudge Brownie",
    "desc": "Rich fudgy brownie served warm with vanilla ice cream.",
    "price": 190,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/brownie.webp",
    "featured": true,
    "available": true,
    "itemId": "dessert-01"
  },
  {
    "title": "Classic Cheesecake",
    "desc": "Silky baked cheesecake with a buttery biscuit base.",
    "price": 220,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/cheesecake.webp",
    "featured": true,
    "available": true,
    "itemId": "dessert-02"
  },
  {
    "title": "Chocolate Tart",
    "desc": "Dark chocolate ganache in a delicate buttery pastry shell.",
    "price": 210,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/chocolate-tart.webp",
    "featured": false,
    "available": true,
    "itemId": "dessert-03"
  },
  {
    "title": "Tiramisu",
    "desc": "Classic coffee-soaked layers with mascarpone and cocoa.",
    "price": 240,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/tiramisu.webp",
    "featured": true,
    "available": true,
    "itemId": "dessert-04"
  },
  {
    "title": "New York Cheesecake",
    "desc": "Rich and creamy cheesecake with a smooth vanilla finish.",
    "price": 250,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/new-york-cheesecake.webp",
    "featured": false,
    "available": true,
    "itemId": "dessert-05"
  },
  {
    "title": "Chocolate Lava Cake",
    "desc": "Warm chocolate cake with a rich molten center.",
    "price": 260,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/lava-cake.webp",
    "featured": true,
    "available": true,
    "itemId": "dessert-06"
  },
  {
    "title": "Ice Cream Sundae",
    "desc": "Vanilla ice cream with chocolate sauce, nuts and cherries.",
    "price": 200,
    "type": "veg",
    "category": "Desserts",
    "section": "food",
    "image": "/menu/sundae.webp",
    "featured": false,
    "available": true,
    "itemId": "dessert-07"
  }
];

const seedMenu = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await MenuItem.deleteMany();
    await MenuItem.insertMany(MENU_DATA);
    console.log("✅ Menu seeded successfully");
    process.exit();
  } catch (err) {
    console.error("❌ Seeding failed", err);
    process.exit(1);
  }
};

seedMenu();
